twitter:
  consumerKey: d8gyOc7Z6jDFab1IDxHT0tJqo
  consumerSecret: gcA3FiqsWqMkX02CyW82tZFScJ4tvOGBiS3z1I3x0fZOdVanqL
  accessToken: 1006233255727726593-MKo4efvt2WEXchTnO7eozNpTylfQSy
  accessSecret: eJuCHfhMHdvfeZogbTFyKLHiXHHsMvEmt2hyZuW9We3MW
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "[%d{HH:mm:ss.SSS}] - %msg %n"
    - type: file
      currentLogFilename: target/log/debug.log
      threshold: ALL
      archive: false
      timeZone: UTC
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%thread] %logger{5} - %X{code} %msg %n"